import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    callback  divide_income(string);

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row{
            Text {
                text: "Enter Total Income";
                font-size: 24px;
                font-weight: 900;
                horizontal-alignment: center;
            }
        }

        Row{
            income:= LineEdit {
                font-size: 16px;
                placeholder-text: "Enter amount";
            }
        }

        Row{
            Button {
                text: "Calculate";
                primary: true;
                clicked => {divide_income(income.text)}
            }
        }

        Row{
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
